baseurl       = "https://pierregarreau.github.io/"
languageCode  = "en-us"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
theme         = "ezhil"
author        = "Pierre Garreau"
title         = "Blog bazar of a Frenchy"
googleAnalytics = "UA-35367847-1"
enableEmoji   = true

[[menu.main]]
name                   = "About"
weight                 = -110
identifier             = "about"
url                    = "/about/"

[[menu.main]]
name                   = "Blog"
weight                 = -120
identifier             = "blog"
url                    = "/blog/"

[params]
  latestpostscount       = 5                             # how many posts to display on the home page
  i18n_flags             = false                         # whether to display small country flags for available translations
  author                 = "Pierre Garreau"
  cachebuster            = true                          # add the current unix timestamp in query string for cache busting css assets
  dateform               = "Jan 2, 2006"
  dateformfull           = "Mon Jan 2 2006 15:04:05 MST"
  description            = "Ideas about code, arts and mathematics."
  email                  = "pierre@garreau.de"
  extracssfiles          = [ "/css/override.css" ]       # In your `static` directory, add/remove files as necessary.
  faviconfile            = "img/leaf.ico"
  github                 = "//github.com/pierregarreau"
  highlightjs            = true
  instagram              = "//instagram.com/theo_calimero"
  lang                   = "en"
  linkedin               = "//linkedin.com/in/pgarreau"
  noshowreadtime         = false                         # if true, don't show "<x> minutes read" in posts
  selfintro              = ""                            # appears in the site header when set to a non-empty string
  twitter                = "//twitter.com/pierre_garreau"
  avatar                 = "img/profile.png" # path to image in static dir e.g img/avatar.png (do not use in the same time as gravatar)
  # gravatar             = ""                # gravatar hash. see https://en.gravatar.com/site/implement/hash/. do not use in the same time as avatar

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "vs"
    tabWidth = 4
